---
title: "Tips"
author: "Steve"
date: "10/26/2021"
output: 
  html_document:
    keep_md: TRUE
---

# 1. Aprender haciendolo

* Kaggle
* Libros
* Tutoriales

# 2. Familiarizate analizando bases de datos

[R for data science](https://r4ds.had.co.nz/)
[Python for data analysis](https://wesmckinney.com/pages/book.html)

# 3. Domina al menos un lenguaje de programación

1. Tidyverse y pandas
2. [Rstudio](https://www.rstudio.com/) y [Anaconda](https://www.anaconda.com/)
3. Rmarkdown y jupyter
4. [Shiny](https://mastering-shiny.org/) y dash

# 4. Utiliza la documentación, stackoverflow y google

Cometer errores es muy común. Apoyarse en documentación, foros y google es parte del flujo de trabajo.

[stackoverflow](https://stackoverflow.com/)

# 5. Entiende y aplica distintos enfoques de inferencia

[Stan](https://mc-stan.org/)

# 6. Aprende a crear paqueterias

R avanzado
[Advanced R](https://adv-r.hadley.nz/)
Git y Github
[Happy Git and GitHub for the useR](https://happygitwithr.com/)

# 7. Carreras profesionales

* Data engineer [IBM Data Engineering Professional Certificate](https://www.coursera.org/professional-certificates/ibm-data-engineer)
* Data analyst [Google Data Analytics Professional Certificate](https://www.coursera.org/professional-certificates/google-data-analytics)
* Data scientist [IBM Data Science Professional Certificate](https://www.coursera.org/professional-certificates/ibm-data-science)

# 8. Sé parte de la comunidad

Usa twitter para conectar con líderes en estadística y ciencia de datos.

Cuentas recomendadas:

[R function a day](https://twitter.com/rfunctionaday)
[Hadley Wickham](https://twitter.com/hadleywickham)
[Cassie Kozyrkov](https://twitter.com/quaesita)

